"""Regex Dictionary"""

# Regex rule to split each file into cases. 
dict_of_regexes = {"american" :{"dict1_usa" : [r"((?!War Crimes Trial Report Number|War Crimea Trial Report No. 1 RSA|War Crimes Trial Report No.3. :ZSTERN|War Crimes Trial Report No.5. i:.111|War Crimes Trial Report No.15. DEPUTY )(?:War Crim.[a-z](?:[a-z]|) Trial \bRe.*?rt\b N(?:[a-z]|.)\.(?:\s|)[0-9](?:[0-9]|)\.?|War Crime[a-z] Thiel Report No\.[0-9](?:[0-9]|)\.|klfans|Heinrich Plaunus|E:iir.|Angust Kobus|ass Trial Report No\.[0-9](?:[0-9]|)\.)\s+(?:\S+\s*){1400})", r"((?:War Crimes Trial HEkl4UARTERS SEVENTH ARMY Report No.10.)\s+(?:\S+\s*){1400})"],
                                "dict2_usa" : [r"((?!War Crimes Trial Report No. 28 HEAD:JJARrEMS|War Crimes Trial Report No. 30 114a1\))(?:\b[0-9A-Z]ar\W+(?:\w+\W+){1,6}?No\b\.(?:\s|)[0-9][0-9](?:\.|)|War Crimes Trial Report No.33. HEADWARTIOIS|Case No: 12-1776 REVIEW|Case No. 12-190 U.S. vs. Karl|War Crimes Trial Report 110.35.)\s+(?:\S+\s*){1300})"],
                                "dict3_usa": [r"((?:\bT[Rr].........\W+(?:\w+\W+){0,5}?at\b)\s(?:\S+\s*){1500})", 
                                       r"((?:TRIaL\W+(?:\w+\W+){0,10} 30 November 1946)\s(?:\S+\s*){1500})",
                                       r"((?:PARTICULARS: In that Ludwig Philip CARL, Robert Hugo DAUB,)\s(?:\S+\s*){1500})",
                                       r"((?:TRIAL DATa: The aocueed were tried at Dachau, Germany, on 13 January 1947)\s+(?:\S+\s*){1500})",
                                       r"((?:TRIAL DATA: The acoused was tried at Daohau, Germany, 4”5 February)\s+(?:\S+\s*){1500})",
                                       r"((?:In that Julius UELTZHOEFFER)\s+(?:\S+\s*){1500})",
                                       r"((?:TRIAL DATAt The accused)\s+(?:\S+\s*){1500})",
                                       r"((?:TRIAL DATA; Tne accused was tried at Dachau, Geraan\^ on 9 May)\s+(?:\S+\s*){1500})",
                                       r"((?:TRIAL DATA: The accused v»as tried at Dachau, Germany, on 29 April)\s+(?:\S+\s*){1500})",
                                       r"((?:PARTICULARS: In that Josof STERN, a Gorman national, did, at or)\s+(?:\S+\s*){1500})",
                                       r"((?:26 December 1946, before a General Military)\s+(?:\S+\s*){1500})",
                                       r"((?:Date: 25 February to 14 March 1946 children. Age 34)\s+(?:\S+\s*){1500})",
                                       r"((?:PARTICULARS: In that Hermann LOUHMF.R NG)\s+(?:\S+\s*){1500})",
                                       r"((?:period 15-14 January 1947\*)\s+(?:\S+\s*){1500})",
                                       r"((?:Germany Dates 14-18 Octoter 1946)\s+(?:\S+\s*){1500})",
                                       r"((?:TRIAL Di.TA)\s+(?:\S+\s*){1500})",
                                       r"((?:period 15-17 ojrll 1947,)\s+(?:\S+\s*){1500})",
                                       r"((?:TRIAL DATAs)\s+(?:\S+\s*){1500})"],
                                "dict4_usa" : [r"((?!Trial bjr|Trial by|Tribunal,|TR \(R 1161|Trmat|Traveling|Trail toy)(?:\bT[Rr]..........(?:\w+\W+){0,5}?at\b|\b[UÜN][N]....+(?:\w+\W+){0,8}?v\b\.)\s+(?:\S+\s*){1500})"],
                                "dict5_usa" : [r"((?!Trial bjr|\b[T].*?(?:l|d)\b (?:[Bb]|h)(?:y|r)|Trial \"by|TYassortruedingen|TlIlHlfl|Ton|Taka|Twice|Two|Tfca|Technical Sergeant|Tall|T[oe]pke|Take|Trial fay|T[Yy]iess|Toit|Tower|Tunnel|Title|To|\b[T].*?ung\b|Tribunal,|TR \(R 1161|Trmat|Traveling|Trail toy)(?:\bT(?!h)[A-Za-z]..........(?:\w+\W+){0,5}?at\b)\s+(?:\S+\s*){1500})"],
                                },
                   "british": {"dict1_british" : [r"(.{150}(?:duly\s*(?:s|.)wor(?:n|)|h[a-z]v[a-z]ng\s*b[a-z][a-z]n d|(?:is|)\s*c[a-z]lled\s*in.\s*[a-z]nd.|and,\s*[sh]avi[a-z][a-z]\s*b[a-z][a-z]n.(?:d|)|duly\s*sw[ao]m|\bT[A-Za-z]+\b \b[Aa][A-Za-z]+\b\s*?(?:\w+\W+){0,2}?\s*?\bh[a-z]+\b\s*\bs[a-z]+\b|\bT[A-Za-z]+\b \b[Aa][A-Za-z]+\b\s*?\s*?(?:\w+\W+){0,2}?\s*?\bt[A-Za-z]+\b h|b[a-z][a-z][nm] (?!dug)du|.[A-Za-z]alled in|\bis\b \bc[aeor](?!n|p)[a-z]+\b in|is \be[a-z]+\b by|t[a-z]k[a-z]s h[a-z]s \bs[a-z]+\b|the court\W(?:\w+\W+){2}?themselves|binding\W(?:\w+\W+){2}?conscience)\s*(?:\S+\s*){1000})"],
                                "dict2_british" : [r"(.{150}(?:duly\s*(?:s|.)wor(?:n|)|h[a-z]v[a-z]ng\s*b[a-z][a-z]n d|(?:is|)\s*c[a-z]lled\s*in.\s*[a-z]nd.|and,\s*[sh]avi[a-z][a-z]\s*b[a-z][a-z]n.(?:d|)|duly\s*sw[ao]m|\bT[A-Za-z]+\b \b[Aa][A-Za-z]+\b\s*?(?:\w+\W+){0,2}?\s*?\bh[a-z]+\b\s*\bs[a-z]+\b|\bT[A-Za-z]+\b \b[Aa][A-Za-z]+\b\s*?\s*?(?:\w+\W+){0,2}?\s*?\bt[A-Za-z]+\b h|b[a-z][a-z][nm] (?!dug)du|.[A-Za-z]alled in|\bis\b \bc[aeor](?!n|p)[a-z]+\b in|is \be[a-z]+\b by|t[a-z]k[a-z]s h[a-z]s \bs[a-z]+\b|the court\W(?:\w+\W+){2}?themselves|binding\W(?:\w+\W+){2}?conscience)\s*(?:\S+\s*){1000})"],
                                # "dict3_british" : [r"(.{150}(?:duly\s*(?:s|.)wor(?:n|)|h[a-z]v[a-z]ng\s*b[a-z][a-z]n d|(?:is|)\s*c[a-z]lled\s*in.\s*[a-z]nd.|and,\s*[sh]avi[a-z][a-z]\s*b[a-z][a-z]n.(?:d|)|duly\s*sw[ao]m|\bT[A-Za-z]+\b \b[Aa][A-Za-z]+\b\s*?(?:\w+\W+){0,2}?\s*?\bh[a-z]+\b\s*\bs[a-z]+\b|\bT[A-Za-z]+\b \b[Aa][A-Za-z]+\b\s*?\s*?(?:\w+\W+){0,2}?\s*?\bt[A-Za-z]+\b h|b[a-z][a-z][nm] (?!dug)du|.[A-Za-z]alled in|\bis\b \bc[aeor](?!n|p)[a-z]+\b in|is \be[a-z]+\b by|t[a-z]k[a-z]s h[a-z]s \bs[a-z]+\b|the court\W(?:\w+\W+){2}?themselves|binding\W(?:\w+\W+){2}?conscience)\s*(?:\S+\s*){1000})"],
                                # "dict4_british" : [r"(.{150}(?:duly\s*(?:s|.)wor(?:n|)|h[a-z]v[a-z]ng\s*b[a-z][a-z]n d|(?:is|)\s*c[a-z]lled\s*in.\s*[a-z]nd.|and,\s*[sh]avi[a-z][a-z]\s*b[a-z][a-z]n.(?:d|)|duly\s*sw[ao]m|\bT[A-Za-z]+\b \b[Aa][A-Za-z]+\b\s*?(?:\w+\W+){0,2}?\s*?\bh[a-z]+\b\s*\bs[a-z]+\b|\bT[A-Za-z]+\b \b[Aa][A-Za-z]+\b\s*?\s*?(?:\w+\W+){0,2}?\s*?\bt[A-Za-z]+\b h|b[a-z][a-z][nm] (?!dug)du|.[A-Za-z]alled in|\bis\b \bc[aeor](?!n|p)[a-z]+\b in|is \be[a-z]+\b by|t[a-z]k[a-z]s h[a-z]s \bs[a-z]+\b|the court\W(?:\w+\W+){2}?themselves|binding\W(?:\w+\W+){2}?conscience)\s*(?:\S+\s*){1000})"],
                                # "dict5_british" : [r"(.{150}(?:duly\s*(?:s|.)wor(?:n|)|h[a-z]v[a-z]ng\s*b[a-z][a-z]n d|(?:is|)\s*c[a-z]lled\s*in.\s*[a-z]nd.|and,\s*[sh]avi[a-z][a-z]\s*b[a-z][a-z]n.(?:d|)|duly\s*sw[ao]m|\bT[A-Za-z]+\b \b[Aa][A-Za-z]+\b\s*?(?:\w+\W+){0,2}?\s*?\bh[a-z]+\b\s*\bs[a-z]+\b|\bT[A-Za-z]+\b \b[Aa][A-Za-z]+\b\s*?\s*?(?:\w+\W+){0,2}?\s*?\bt[A-Za-z]+\b h|b[a-z][a-z][nm] (?!dug)du|.[A-Za-z]alled in|\bis\b \bc[aeor](?!n|p)[a-z]+\b in|is \be[a-z]+\b by|t[a-z]k[a-z]s h[a-z]s \bs[a-z]+\b|the court\W(?:\w+\W+){2}?themselves|binding\W(?:\w+\W+){2}?conscience)\s*(?:\S+\s*){1000})"],
                                # "dict6_british" : [r"(.{150}(?:duly\s*(?:s|.)wor(?:n|)|h[a-z]v[a-z]ng\s*b[a-z][a-z]n d|(?:is|)\s*c[a-z]lled\s*in.\s*[a-z]nd.|and,\s*[sh]avi[a-z][a-z]\s*b[a-z][a-z]n.(?:d|)|duly\s*sw[ao]m|\bT[A-Za-z]+\b \b[Aa][A-Za-z]+\b\s*?(?:\w+\W+){0,2}?\s*?\bh[a-z]+\b\s*\bs[a-z]+\b|\bT[A-Za-z]+\b \b[Aa][A-Za-z]+\b\s*?\s*?(?:\w+\W+){0,2}?\s*?\bt[A-Za-z]+\b h|b[a-z][a-z][nm] (?!dug)du|.[A-Za-z]alled in|\bis\b \bc[aeor](?!n|p)[a-z]+\b in|is \be[a-z]+\b by|t[a-z]k[a-z]s h[a-z]s \bs[a-z]+\b|the court\W(?:\w+\W+){2}?themselves|binding\W(?:\w+\W+){2}?conscience)\s*(?:\S+\s*){1000})"],
                               }
                   }
snippet_rules_dict = {"name_snippet" : r"((?:\S+\s+){0,0}(?:[A-Z]n t[a-zA-Z][a-zA-Z]t \b[A-Z].*?\b\b[A-Z].*?\b|[Tt]he a[a-z][a-z][a-z][a-z][a-z]d \b[A-Z].*?\b\b[A-Z].*?\b[A-Z]|in the case of the Accused|Particulars: In that|United States vs. Frans|Heinrich OTTE|Heinrich Plaunus Nikolaus ?achinger|: In that)\s*(?:\S+\s*){0,30})",              
                      "place_snippet": r"((?!near a|near the|at \b[D].*?au\b, Germany|at Heidelberg|at \b[L].*?urg\b|General)(?:at or near|at \b[a-z][a-z]\b n..r|near|[Ii]n the neighborhood|did, at \b[A-Z].*?\b|in th[a-z] vicinity of|th[a-z] vicinity of|at sundry places within the then German Reich)\s+(?:\S+\s*){5})",
                      "age_snippet" : r"(?:[0-9][0-9] y[a-z][a-z][a-z][a-z] of (?:a[a-z][a-z]|)|(?:(?:[Aa]g[a-z]|oge)(?:\s+\S+|\W+){0,2}?(?:n|\s)(?:[A-Z][0-9]|[a-z][0-9]|\d{2}\b))|AGE: 37|\\nGerman\\n\d{2}|[a-z]g[a-z]: \d{2})",
                      "occupation_snippet" : r"(.{75}(?:Civilian [Ss]tatus|[Mm]ilitary [a-z]tatus|[Pp]arty [Ss]tatus|[aA]ttended school|Labor Service|Rank:|by ocemation|by occupation)\s*(?:\S+\s*){25})",
                      "defense_snippet": r"(.{250}(?:THE DEFENSE:|The accused stated|Evidence for the Prosecution|Evidence for Prosecution:|SUMM.RY OF E|F EVIDENCE|c[a-z]nf[a-z]ssion|.uilt.|.dmit|w[a-z]llf[a-z]lly)\s*(?:\S+\s*){300})",
#             "name_snippet2": r"^((?:\S+\s+){200}\S+)",
             }

bestguess_rules_dict = {
              "capitalized_words1" : r"(?!Ko(?:n|)zentrationslager|Wie| Dac[a-z]au|Seventh United|Orders|Parent|Crime[a-z]|[A-Z]a[a-z]hau|Head[a-z]u[a-z]rters|W[a-z]r|Third|The Un[a-z]t[a-z]d|[WVRN](?:i|)ar |[WVRN](?:i|)ar Crime[a-zA-Z]|Trial(?:s|)|T[a-z][a-z][a-z][a-z] Report|Crime[a-z] T[a-z][a-z][a-z][a-z]|Report No|Commanding|Case|No|[UL][nh]it[a-z]d|Government|Stat[a-z]s|Third|Mauth[a-z][a-z]sen|Penal|Bolson|Forc[a-z]s|[GC](?:r|)[a-z][a-z]man|Army|US|The.Trial|THE.TRIAL|Intermediate|[MV]ilita[a-z]y|G[oe]n[oe][a-z][a-z]l|[A-Z](?:i)lita[a-z]y|[A-Z]rosecution|Major|War Criminals|Da[a-z][hn]au Con[a-z]entration|D[a-z]c[nh][a-z][Uu]|Court|Review. Verf|General|S[a-z]rg[a-z][a-z]nt|[A-Z]ec[a-z]nician|[A-Z]ifth|Grade|Station|Lieutenant|Captain|Sixth|Twelfth|Air|Under|Article|Commission|Group|First|European Theater|Theater|Seventh|Juke|Unitary|Office|[YF]inding Charge|P[aA][Rr][tT][Ii][Cc][Uu][Ll][Aa][Rr](?:[Ss]|)|International|Prosecutions|Dies[a-z]|D[a-z]r|From|D[a-z][a-z]uty|Deputy Judge|Judge|Judge Advocate|[CS]taff Judge|First Military|General Firs.|Accused N[a-z][a-z][a-z]|G[a-z][a-z][a-z][a-z][a-z][a-z][a-z][a-z]|Brigadier General|[OG]eneral.|Civilian|Home|Assistant|Oberen|Conc[a-z]ntr[a-z]t[a-z]on C[ao]mp|Crimes Group|Criminal Law|Cr[a-z]m[a-z]n[a-z]l|Camp|H[a-z]ndl[a-z]ng|Special Orders|Review|Police Chief|Police|Ludwig[a-z]burg|Sp[a-z]cial Orders|A[a-z]med Forces|Int[a-z]rm[a-z]di[a-z]t[a-z] Military|Hitler Youth|Labor Service|Concentration|Lacoau|Th[a-z]|Western|Eastern)\b([A-Z][a-z]\w+.[A-Z]\w+)\b",
              "capitalized_words2" : r"(?!S[a-z]v[a-z][a-z]t|Fl[a-z]ss[a-z]nb(?:lu|)[a-z]rg|Witness|B[a-z][a-z][nh]en(?:w|)(?:a|)ld|Staff|Castle|Forest|Related|G[a-z]rman Army|Sub-Camps|Viar|S[a-z]c[a-z]nd|Grand|D[a-z][a-z]hy|C(?:[a-z]|)mp|Bad|L[a-z]ng[a-z]nf[a-z]ld|M[a-z]m[a-z]r[a-z]nd[a-z]m|British|Inc[a-z]d[a-z]nts|Ch[a-z]rge|Tsar|Defense|American|Ihrent|[A-Z][a-z]rty|Gros(?:s|)-[HR]aming|Cr[a-z][a-z][a-z](?:[a-zA-Z]|PiuiTICULnjtS)|Factory|Na[a-z]i|Polish|Russian|Czech|Jew|T[a-z]chnical|Serial|C[a-z]mm[a-z]nding|Oestern|Protestant|For|Waz|Ass|Hiss|CiRTIFIdtTE|CrirlBHlt|Eigth|Convening|Caanandlng Oanaral|Ragulationa Oevemlag|Oanaral Headquarters|Mar|E[a-z]r[a-z]p[a-z][a-z]n|Goman|Hitler Jugend|Internment|Flossenblirg|Gros^Raming)\b([A-Z][a-z]\w+.[A-Z]\w+)\b",
              "capitalized_words3" : r"(?![PF]lea(?:s|)|Acc[a-z][a-z][a-z][a-z]|Gern6n|Bruchsel|Sp[a-z]c[a-z]al|R[a-z]d|Various|Private|Antitank|Yokohama|Auschwitz|[FP]rison|Adjutant|Jar|Nur|Jahr|Germain|Adv[a-z][a-z][a-z]t[a-z]|Her|City|Aar|Monaten|Flight|Palm|Control|All[a-z][a-z]d|Tbr|Cr[a-z][a-z][a-z]s|Yiar|Spanish|Florisdorf|OpttritAir|Jwia41oLiun|Nriviii.Asion|Comments|Krei3|Guilty|N[a-z]t|Gross|Nisi|Harvard|California|Asst|Service|Jurisdictional|Aid|District|Ort|UmbemembeWxockviederommeemimmonerx Copy|Kamrfgruppe Schwaben|A(?:r|)[nm]y|Stuff|Liilitary|Certain|Anglo-American|Masi|Heil|Merican|Evidence|Specifications|[EF]uropean|Security|A[a-z]vocate|St[a-z]t[a-z]s|Supreme|Procedure|Investigating|Law)\b([A-Z][a-z]\w+.[A-Z]\w+)\b",              
              "capitalized_words4" : r"(?!\bL.*?ary\b|\bL.*?ant\b|\b[A-Z].*?\b \bCon.*?[oe]n\b|\b[Jj].*?\b \b[Aa].*?ate\b|New Evidence|\b[F].*?rg\b \bC.*?[e]n\b|Chief|Agent|Italian|Post|Master|Employee|Hungarian|\b[M].*?on\b \bC.*?[oe]n\b|Concentration)\b([A-Z][a-z]\w+.[A-Z]\w+)\b",
#               "extract_places" : r"([A-Z](?:[A-Z]|[a-z])+)",
              "extract_places" : r"([A-Z]\w+, [A-Z]\w+)",
              "extract_origin" : r".{20}(?=b[a-z][a-z]n in|).{50}",
              "extract_age" : r"(?!u00|00|\bu[0-9][0-9][0-9][0-9]\b|[0-9][0-9].[a-xA-X]|n[0-9][0-9].[a-xA-X]|[0-9][0-9]\)|[0-9](?:[0-9]|) years commencing|[0-9][0-9]\.)(?:\b[0-9][0-9]\b|[A-Z][0-9][0-9]|\b[a-z][0-9][0-9]\b|\b\\\\n[0-9][0-9]\b)",
              "extract_occupation" : r"((?!Findings|Sentence|Nationality|Civilian Status\W+(?:\w+\W+){0,1}Status)(?:Civilian Status(?::|)|\\\\[A-Za-z]+\\\\[a-z][0-9][0-9]\\\\[A-Za-z]+|[aA]ttended school|\\\\[a-z][0-9][0-9]\\\\[A-Za-z]+)\s*(?:\S+\s*){0,3})",
#              "defense_snippet": r"((?:\S+\s+){50}(?:c[a-z]nf[a-z]ssion|.uilt.|.dmit|w[a-z]llf[a-z]lly)\s*(?:\S+\s*){50})",
              # "defense_snippet2": r"((?:\S+\s+){50}(?:s[a-z]perior.order.|order)\s*(?:\S+\s*){50})"
              }

# I will make dictionary of dictionary later
snippet_rules_dict_british = {"name_snippet": r"((?:\bW[a-z]{3}\b is \b.{4}\b full \b.{4}\b|\bW[a-z]{3}\b is \b.{4}\b \b.{4}\b|\by[a-z]+\b f[a-z]ll|What are your full names|[A-Za-z]our name|\bn[a-z]{3}\b\?|Are your full names|full names|(?:Q|) Are you [a-zA-Z]|lull mimes|you tell\W+(?:\w+\W+){3}?your|Is [yJ]our|Q [Yy]our \b.{4}\b|Q I[sn] \b\y..rb|i[sn] y...(?:.|) n|(give|tell) the court your)\s*(?:\S+\s*){30})",
                              "place_snippet" : r"((?:[Dd]o you live|live by|live near|Do \b[a-z]{3}\b l[a-z]ve|Where are you from|Where do you live|where \b[a-z]{2}\b \b[a-z]{3}\b live|where were you living|and address|Are y.. fr[a-z][a-z]|Are you of|And where|resident of|did you hold at|live in)\s*(?:\S+\s*){30})",
                              "age_snippet": r"(.{20}(?:years old|\by[a-z]{4}\b of (?:ag[a-z]|a.e|)|H[a-z]w \b\[a-z]{3}b are you|old are you|\bH[a-z]{2}\b (?:old|...) are you|\b[a-z]ge|you b[a-z][a-z]n|born on|When were you born).{30})",
                              "occupation_snippet" : r".{20}(?:[a-z]mpl[a-z]y.ent|rank|o[a-z][a-z][a-z][a-z][a-z]tion|job|trade|o..up.tion|civil p|[a-z].ployed|What was (?:.{3}|.{4}) occupation|\boc(?:.{8}|.{6}|.{7}|.{9})on\b|How w[a-z]r[a-z] you e....yed|In what c....ity w|your pr.....ion|I worked|Where did you work|What was your position).{30}",
                              "guilt_snippet": r"[a-z][a-z]ilty.or.[a-z]ot.[a-z][a-z]ilty.{100}|[a-z][a-z]ilty.to.{100}|.{50}[a-z]uilt[a-z].{200}|((\bg(?:[a-z]{4}|[a-z]{5})\b\W(?:\w+\W+){2}\bg(?:[a-z]{4}|[a-z]{5})\b).{200})",
                              "orders_snippet": r".{300}obey.{300}|.{300}ordered.{300}|.{100}willful.{200}|.{100}authority.{100}|.{100}superior.orders.{300}|.{100}refused.{300}|.{300}take.part.{300}|.{50}execution.{300}|.{50}law.of.war.{100}",
                              }


bestguess_rules_dict_british = {"extract_name":r"((?!A[a-z][a-z]|Hannover|Berlin|What|Major|And|Company|Were|March|Yes|Captain|Tour|You|Dreierwrlde|Haw|Where|At|German|Aare|Teach|ASt|Yee|Yo|Yen|Wa|Y[a-z][a-z]|Is|Do|Ine|Cant|Tee|When|Between|How|No|Teas|Set|Investigation|Team|It|Twenty|BQ4|Direktor|Gestapo|Head.......|Ho|Well|As|That|Ow|On|Thank|The|LT|PRESIDENT|General|G[a-z]rman|February|A0)[A-Z]\w+)",
                           "extract_place":"",
                           "extract_age":"",
                           "extract_occupation":"",
                           "extract_defense":"", 
                              
    }